/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutComponent: typeof import('./src/components/AboutComponent.vue')['default']
    AddLocation: typeof import('./src/components/AddLocation.vue')['default']
    AddZones: typeof import('./src/components/AddZones.vue')['default']
    AdminBooking: typeof import('./src/components/AdminBooking.vue')['default']
    AlgSection: typeof import('./src/components/AlgSection.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    DeleteAnimal: typeof import('./src/components/DeleteLocation.vue')['default']
    DeleteLocation: typeof import('./src/components/DeleteLocation.vue')['default']
    DeleteZones: typeof import('./src/components/DeleteZones.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LocationCard: typeof import('./src/components/LocationCard.vue')['default']
    NavMenue: typeof import('./src/components/NavMenue.vue')['default']
    PokeFooter: typeof import('./src/components/PokeFooter.vue')['default']
    RevComponent: typeof import('./src/components/RevComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SellCompornt: typeof import('./src/components/SellCompornt.vue')['default']
  }
}
